defmodule Indie.Markdown.VideoTransformer do
  @moduledoc """
  Pre-processor that transforms [video:/path/to/file.mp4] shorthand into
  a <video> HTML block with WebM (VP9) as the primary source and MP4 (H.264)
  as the fallback.

  Syntax:
      [video:/videos/my-screencap.mp4]

  Output:
      <video controls width="100%">
      <source src="/videos/my-screencap.webm" type="video/webm" />
      <source src="/videos/my-screencap.mp4" type="video/mp4" />
      </video>

  Self-closing `<source />` syntax is required so Earmark does not try to find
  a matching `</source>` closing tag (source is not in Earmark's void_tags list).

  The .webm sibling is assumed to live at the same path with a .webm extension,
  generated by `mix videos.optimize`.
  """

  @video_pattern ~r/\[video:([^\]]+\.mp4)\]/

  @doc """
  Scans `markdown` for [video:...] tags and replaces each with a <video> HTML block.
  Returns the modified markdown string.
  """
  @spec transform(String.t()) :: String.t()
  def transform(markdown) do
    Regex.replace(@video_pattern, markdown, fn _full, path ->
      webm_path = String.replace_suffix(path, ".mp4", ".webm")

      """
      <video controls width="100%" preload="none">
      <source src="#{webm_path}" type="video/webm" />
      <source src="#{path}" type="video/mp4" />
      </video>
      """
      |> String.trim_trailing()
    end)
  end
end
