defmodule Indie.WritingExercises.Tagger do
  @moduledoc """
  A lightweight Brill-style POS tagger tuned for adjective/adverb detection.
  Uses a hardcoded lexicon for function words (determiners, pronouns, verbs,
  prepositions, conjunctions), the Grady Ward Moby POS lexicon for
  adjectives and adverbs, suffix rules for unknown words, and falls back
  to noun for completely unknown words.
  """

  @lexicon %{
    # adjectives
    "beautiful" => :adj,
    "quick" => :adj,
    "slow" => :adj,
    "loud" => :adj,
    "quiet" => :adj,
    "bright" => :adj,
    "dark" => :adj,
    "big" => :adj,
    "small" => :adj,
    "tall" => :adj,
    "short" => :adj,
    "long" => :adj,
    "wide" => :adj,
    "narrow" => :adj,
    "deep" => :adj,
    "shallow" => :adj,
    "hot" => :adj,
    "cold" => :adj,
    "warm" => :adj,
    "cool" => :adj,
    "old" => :adj,
    "young" => :adj,
    "new" => :adj,
    "fresh" => :adj,
    "clean" => :adj,
    "dirty" => :adj,
    "rich" => :adj,
    "poor" => :adj,
    "strong" => :adj,
    "weak" => :adj,
    "hard" => :adj,
    "soft" => :adj,
    "heavy" => :adj,
    "light" => :adj,
    "thick" => :adj,
    "thin" => :adj,
    "empty" => :adj,
    "full" => :adj,
    "flat" => :adj,
    "round" => :adj,
    "sharp" => :adj,
    "dull" => :adj,
    "sweet" => :adj,
    "sour" => :adj,
    "bitter" => :adj,
    "salty" => :adj,
    "dry" => :adj,
    "wet" => :adj,
    "loose" => :adj,
    "tight" => :adj,
    "calm" => :adj,
    "clear" => :adj,
    "fair" => :adj,
    "fine" => :adj,
    "firm" => :adj,
    "free" => :adj,
    "glad" => :adj,
    "good" => :adj,
    "grand" => :adj,
    "great" => :adj,
    "harsh" => :adj,
    "huge" => :adj,
    "kind" => :adj,
    "lean" => :adj,
    "low" => :adj,
    "mild" => :adj,
    "neat" => :adj,
    "nice" => :adj,
    "odd" => :adj,
    "pale" => :adj,
    "pure" => :adj,
    "rare" => :adj,
    "raw" => :adj,
    "real" => :adj,
    "ripe" => :adj,
    "rude" => :adj,
    "safe" => :adj,
    "sick" => :adj,
    "slim" => :adj,
    "sore" => :adj,
    "sure" => :adj,
    "tiny" => :adj,
    "true" => :adj,
    "vast" => :adj,
    "wild" => :adj,
    "wise" => :adj,
    "wrong" => :adj,
    "brown" => :adj,
    "gray" => :adj,
    "grey" => :adj,
    "purple" => :adj,
    "orange" => :adj,
    "pink" => :adj,
    "gold" => :adj,
    "silver" => :adj,
    "lovely" => :adj,
    "friendly" => :adj,
    "costly" => :adj,
    "lively" => :adj,
    "comely" => :adj,
    "unlikely" => :adj,
    "likely" => :adj,
    "early" => :adj,
    "elderly" => :adj,
    "ghostly" => :adj,
    "hourly" => :adj,
    "daily" => :adj,
    "weekly" => :adj,
    "monthly" => :adj,
    "yearly" => :adj,
    "heavenly" => :adj,
    "homely" => :adj,
    "manly" => :adj,
    "motherly" => :adj,
    "scholarly" => :adj,
    "silly" => :adj,
    "ugly" => :adj,
    "wily" => :adj,
    "red" => :adj,
    "blue" => :adj,
    "green" => :adj,
    "yellow" => :adj,
    "white" => :adj,
    "black" => :adj,
    "happy" => :adj,
    "sad" => :adj,
    "smart" => :adj,
    "brave" => :adj,
    "certain" => :adj,
    "alone" => :adj,
    "eager" => :adj,
    "lucky" => :adj,
    "proud" => :adj,
    "pleasant" => :adj,
    "pleased" => :adj,
    "keen" => :adj,
    "broad" => :adj,
    "handy" => :adj,
    "main" => :adj,
    "minor" => :adj,
    "noble" => :adj,
    "steady" => :adj,
    "steep" => :adj,
    "ready" => :adj,

    # adverbs
    "very" => :adv,
    "quite" => :adv,
    "too" => :adv,
    "almost" => :adv,
    "well" => :adv,
    "soon" => :adv,
    "now" => :adv,
    "then" => :adv,
    "here" => :adv,
    "there" => :adv,
    "always" => :adv,
    "never" => :adv,
    "often" => :adv,
    "sometimes" => :adv,
    "usually" => :adv,
    "already" => :adv,
    "still" => :adv,
    "yet" => :adv,
    "again" => :adv,
    "ever" => :adv,
    "even" => :adv,
    "rather" => :adv,
    "hardly" => :adv,
    "barely" => :adv,
    "nearly" => :adv,
    "merely" => :adv,
    "simply" => :adv,
    "mostly" => :adv,
    "largely" => :adv,
    "mainly" => :adv,
    "greatly" => :adv,
    "deeply" => :adv,
    "widely" => :adv,
    "highly" => :adv,
    "plainly" => :adv,
    "probably" => :adv,
    "certainly" => :adv,
    "definitely" => :adv,
    "absolutely" => :adv,
    "slightly" => :adv,
    "somewhat" => :adv,
    "pretty" => :adv,
    "fairly" => :adv,
    "just" => :adv,
    "only" => :adv,
    "really" => :adv,
    "also" => :adv,
    "so" => :adv,
    "not" => :adv,
    "no" => :adv,
    "off" => :adv,
    "less" => :adv,
    "more" => :adv,
    "most" => :adv,
    "maybe" => :adv,
    "perhaps" => :adv,
    "please" => :adv,

    # determiners
    "the" => :det,
    "a" => :det,
    "an" => :det,
    "this" => :det,
    "that" => :det,
    "these" => :det,
    "those" => :det,
    "some" => :det,
    "any" => :det,
    "every" => :det,
    "each" => :det,
    "all" => :det,
    "both" => :det,
    "few" => :det,
    "many" => :det,
    "several" => :det,
    "much" => :det,
    "what" => :det,
    "which" => :det,
    "whose" => :det,

    # pronouns
    "i" => :pron,
    "you" => :pron,
    "he" => :pron,
    "she" => :pron,
    "it" => :pron,
    "we" => :pron,
    "they" => :pron,
    "me" => :pron,
    "him" => :pron,
    "her" => :pron,
    "us" => :pron,
    "them" => :pron,
    "my" => :pron,
    "your" => :pron,
    "his" => :pron,
    "its" => :pron,
    "our" => :pron,
    "their" => :pron,
    "mine" => :pron,
    "yours" => :pron,
    "hers" => :pron,
    "ours" => :pron,
    "theirs" => :pron,
    "myself" => :pron,
    "yourself" => :pron,
    "himself" => :pron,
    "herself" => :pron,
    "itself" => :pron,
    "ourselves" => :pron,
    "themselves" => :pron,
    "someone" => :pron,
    "something" => :pron,
    "anyone" => :pron,
    "anything" => :pron,
    "nothing" => :pron,
    "nobody" => :pron,
    "everyone" => :pron,
    "everything" => :pron,
    "who" => :pron,
    "whom" => :pron,
    "whoever" => :pron,

    # verbs (common auxiliary + be verbs, plus sample action verbs)
    "is" => :vb,
    "are" => :vb,
    "was" => :vb,
    "were" => :vb,
    "be" => :vb,
    "been" => :vb,
    "being" => :vb,
    "have" => :vb,
    "has" => :vb,
    "had" => :vb,
    "having" => :vb,
    "do" => :vb,
    "does" => :vb,
    "did" => :vb,
    "done" => :vb,
    "will" => :vb,
    "would" => :vb,
    "could" => :vb,
    "should" => :vb,
    "may" => :vb,
    "might" => :vb,
    "can" => :vb,
    "shall" => :vb,
    "must" => :vb,
    "need" => :vb,
    "dare" => :vb,
    "ought" => :vb,
    "go" => :vb,
    "went" => :vb,
    "gone" => :vb,
    "going" => :vb,
    "run" => :vb,
    "ran" => :vb,
    "say" => :vb,
    "said" => :vb,
    "make" => :vb,
    "made" => :vb,
    "take" => :vb,
    "took" => :vb,
    "come" => :vb,
    "came" => :vb,
    "see" => :vb,
    "saw" => :vb,
    "know" => :vb,
    "knew" => :vb,
    "get" => :vb,
    "got" => :vb,
    "give" => :vb,
    "gave" => :vb,
    "find" => :vb,
    "found" => :vb,
    "think" => :vb,
    "thought" => :vb,
    "tell" => :vb,
    "told" => :vb,
    "walk" => :vb,
    "stand" => :vb,
    "sit" => :vb,
    "look" => :vb,
    "feel" => :vb,
    "held" => :vb,
    "hold" => :vb,
    "let" => :vb,
    "keep" => :vb,
    "set" => :vb,
    "put" => :vb,
    "begin" => :vb,
    "show" => :vb,
    "hear" => :vb,
    "ask" => :vb,
    "turn" => :vb,
    "move" => :vb,
    "try" => :vb,
    "call" => :vb,
    "pull" => :vb,
    "push" => :vb,
    "reach" => :vb,
    "open" => :vb,
    "close" => :vb,
    "speak" => :vb,
    "eat" => :vb,
    "drink" => :vb,
    "write" => :vb,
    "read" => :vb,
    "sleep" => :vb,
    "throw" => :vb,
    "catch" => :vb,
    "lift" => :vb,
    "drop" => :vb,
    "carry" => :vb,
    "bring" => :vb,
    "buy" => :vb,
    "build" => :vb,
    "grow" => :vb,
    "live" => :vb,
    "die" => :vb,
    "sing" => :vb,
    "dance" => :vb,
    "laugh" => :vb,
    "cry" => :vb,
    "shout" => :vb,
    "whisper" => :vb,
    "smile" => :vb,
    "frown" => :vb,
    "stare" => :vb,
    "glance" => :vb,
    "gaze" => :vb,
    "touch" => :vb,
    "grab" => :vb,
    "squeeze" => :vb,
    "release" => :vb,

    # prepositions
    "in" => :prep,
    "on" => :prep,
    "at" => :prep,
    "for" => :prep,
    "to" => :prep,
    "with" => :prep,
    "by" => :prep,
    "from" => :prep,
    "of" => :prep,
    "about" => :prep,
    "into" => :prep,
    "through" => :prep,
    "during" => :prep,
    "before" => :prep,
    "after" => :prep,
    "above" => :prep,
    "below" => :prep,
    "between" => :prep,
    "under" => :prep,
    "over" => :prep,
    "without" => :prep,
    "within" => :prep,
    "along" => :prep,
    "around" => :prep,
    "behind" => :prep,
    "beside" => :prep,
    "beyond" => :prep,
    "across" => :prep,
    "against" => :prep,
    "among" => :prep,
    "toward" => :prep,
    "towards" => :prep,
    "inside" => :prep,
    "outside" => :prep,
    "upon" => :prep,
    "past" => :prep,
    "until" => :prep,
    "since" => :prep,

    # conjunctions
    "and" => :conj,
    "or" => :conj,
    "but" => :conj,
    "nor" => :conj,
    "because" => :conj,
    "if" => :conj,
    "though" => :conj,
    "although" => :conj,
    "while" => :conj,
    "when" => :conj,
    "where" => :conj,
    "as" => :conj,
    "than" => :conj,
    "unless" => :conj,
    "whether" => :conj,
    "once" => :conj,

    # common nouns that would be caught by suffix rules
    "butterfly" => :nn,
    "firefly" => :nn,
    "dragonfly" => :nn,
    "assembly" => :nn,
    "family" => :nn,
    "supply" => :nn,
    "reply" => :nn,
    "ally" => :nn,
    "body" => :nn,
    "study" => :nn,
    "city" => :nn,
    "party" => :nn,
    "story" => :nn,
    "lady" => :nn,
    "baby" => :nn,
    "entry" => :nn,
    "industry" => :nn,
    "victory" => :nn
  }

  @suffix_rules [
    {~r/ly$/, :adv},
    {~r/ful$/, :adj},
    {~r/ous$/, :adj},
    {~r/ive$/, :adj},
    {~r/able$/, :adj},
    {~r/ible$/, :adj},
    {~r/less$/, :adj},
    {~r/ic$/, :adj},
    {~r/al$/, :adj},
    {~r/ary$/, :adj},
    {~r/ent$/, :adj},
    {~r/ant$/, :adj},
    {~r/ish$/, :adj},
    {~r/ory$/, :adj},
    {~r/ward$/, :adv},
    {~r/wise$/, :adv},
    {~r/some$/, :adj},
    {~r/like$/, :adj}
  ]

  @doc """
  Tags a single word with its part of speech.

  Checks hardcoded lexicon first (for function words), then the Moby POS
  lexicon (for adjectives/adverbs), then suffix rules, and falls back to
  :nn (noun) for completely unknown words.
  """
  alias Indie.WritingExercises.Lexicon

  def tag(word) when is_binary(word) do
    lower = String.downcase(word)

    case Map.get(@lexicon, lower) do
      nil ->
        cond do
          Lexicon.adjective?(lower) -> :adj
          Lexicon.adverb?(lower) -> :adv
          true -> match_suffix(lower) || :nn
        end

      tag ->
        tag
    end
  end

  @doc """
  Tags a list of words. Each result is `%{word: original_string, tag: atom}`.
  """
  def tag_words(words) when is_list(words) do
    Enum.map(words, fn word ->
      %{word: word, tag: tag(word)}
    end)
  end

  defp match_suffix(word) do
    Enum.find_value(@suffix_rules, fn {regex, tag} ->
      if String.match?(word, regex), do: tag
    end)
  end
end
